In [ ]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [ ]:
import tensorflow as tf
tf.__version__

'2.2.0'

In [ ]:
tf.constant(6)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [ ]:
tf.constant(6.)

<tf.Tensor: shape=(), dtype=float32, numpy=6.0>

In [ ]:
tf.constant([True,False])

<tf.Tensor: shape=(2,), dtype=bool, numpy=array([ True, False])>

In [ ]:
tf.constant('I love tf2!!!')

<tf.Tensor: shape=(), dtype=string, numpy=b'I love tf2!!!'>

 **變數類型**

In [ ]:
import numpy as np

In [ ]:
#Create tf.constant
a = tf.constant([1,2,3])
#Convert np arry to tf
a = np.array([1,2,3])
b = tf.convert_to_tensor(a)

In [ ]:
a

array([1, 2, 3])

In [ ]:
b

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [ ]:
#Create tf.Variable
a = tf.ones(6)
b = tf.Variable(a,name='Data_point')
b

<tf.Variable 'Data_point:0' shape=(6,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
b.trainable #check weather trainable

True

**建立數據**

In [ ]:
#Create 0 matrix
a = tf.zeros([6,6])
#or
b = tf.zeros_like(a)
#or fill -> shape and fill nums
c = tf.fill([6,6],0)

In [ ]:
a

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
b

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [ ]:
c

<tf.Tensor: shape=(6, 6), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]], dtype=int32)>

In [ ]:
#Example random by normal distribution
a = tf.random.normal([6,6],mean=0,stddev=1)
#random by truncated normal distribution
b = tf.random.truncated_normal([6,6],mean=0,stddev=1)
#random by uniform
c = tf.random.uniform([6,6],minval=0,maxval=1)

In [ ]:
a

<tf.Tensor: shape=(6, 6), dtype=float32, numpy=
array([[-0.86769944, -0.19918764,  0.34136266,  0.9650739 , -1.0503021 ,
         1.3500249 ],
       [ 1.6759603 , -0.82143515,  0.91301703, -0.7245867 , -0.40288413,
         0.01441614],
       [-1.3158898 , -0.34044948,  1.110268  ,  0.02878339, -0.8650245 ,
         0.92250246],
       [ 0.14821306,  0.3656436 , -0.5958695 ,  0.2909478 , -0.39661515,
        -0.58923286],
       [-0.47943792, -0.8935525 ,  2.1721327 ,  1.0906124 ,  0.4877502 ,
        -0.2911349 ],
       [ 0.9014349 , -0.43325078,  0.56858754,  1.5336782 ,  0.40814406,
        -0.47223693]], dtype=float32)>

**數據操作**

**使用類似Python原本的slice方法**

In [ ]:
#Example for select instance
a = tf.ones([1,5,5,3]) #4維資料
a[0][0].shape
#Output shape:TensorShape([5, 3])
a[...,2].shape
#Output shape:TensorShape([1, 5, 5])

In [ ]:
a

In [ ]:
a[0][0]

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [ ]:
a[...,2]

<tf.Tensor: shape=(1, 5, 5), dtype=float32, numpy=
array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]], dtype=float32)>

**使用TF2的API的操作索引(index)**

In [ ]:
#use index select
tf.gather_nd(a,[0]).shape
#Output shape: TensorShape([5, 5, 3])

#select axis=1 , row 2 and 3
tf.gather(a,axis=1,indices=[2,3]).shape
#Output shape: TensorShape([1, 2, 5, 3])

TensorShape([1, 2, 5, 3])

In [ ]:
tf.gather(a,axis=1,indices=[2,3])

<tf.Tensor: shape=(1, 2, 5, 3), dtype=float32, numpy=
array([[[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]], dtype=float32)>

In [ ]:
tf.gather_nd(a,[0])

<tf.Tensor: shape=(5, 5, 3), dtype=float32, numpy=
array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]], dtype=float32)>

In [ ]:
#處理梯度爆炸問題
#設定特定門檻值
#Example clipping

tf.clip_by_value(data,0,1)
#range if number less or above fix at 0 or 1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.       , 0.8009505, 1.       ],
       [0.441546 , 0.       , 0.       ],
       [0.       , 0.7639621, 0.9443403]], dtype=float32)>

In [ ]:
#Example argmax
#常用情境:於當模型輸出所有分類的預測結果時，直接取用機率最高之分類作為預測結果
#會回傳最大數值的索引

a = tf.constant([1,2,3])
tf.math.argmax(a)

<tf.Tensor: shape=(), dtype=int64, numpy=2>