In [1]:
try:
  # %tensorflow_version only exists in Colab.
  %tensorflow_version 2.x
except Exception:
  pass

In [2]:
import tensorflow as tf

tf.__version__


'2.2.0'

In [ ]:
a = tf.constant(6)
b = tf.constant(6)
c = tf.add(a,b)

print(c)


tf.Tensor(12, shape=(), dtype=int32)


In [ ]:
#建立函式
@tf.function
def simple_nn_layer(x, y):
  return tf.nn.relu(tf.matmul(x, y))


x = tf.random.uniform((2, 2))
y = tf.random.uniform((2, 2))

simple_nn_layer(x, y)

<tf.Tensor: id=306, shape=(2, 2), dtype=float32, numpy=
array([[0.53198206, 0.8045535 ],
       [0.20539649, 0.43102896]], dtype=float32)>

In [ ]:
import numpy as np


In [ ]:
a = np.array([1,2,3])
b = tf.convert_to_tensor(a)
b

<tf.Tensor: id=307, shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

In [ ]:
a = tf.ones(6)
b = tf.Variable(a,name='Data_point')
b

<tf.Variable 'Data_point:0' shape=(6,) dtype=float32, numpy=array([1., 1., 1., 1., 1., 1.], dtype=float32)>

In [ ]:
b.dtype

tf.float32

In [ ]:
b.name

'Data_point:0'

In [ ]:
b.trainable

True

In [ ]:
a = tf.zeros([6,6])
a

In [ ]:
b = tf.zeros_like(a)
b

In [ ]:
tf.fill([6,6],0)

In [ ]:
tf.random.normal([6,6],mean=0,stddev=1)

In [ ]:
tf.random.uniform([6,6],minval=0,maxval=1)

In [ ]:
tf.random.truncated_normal([6,6],mean=0,stddev=1)

**數據操作方法**

In [4]:
a = tf.ones([1,5,5,3])

In [5]:
a[0][0].shape

TensorShape([5, 3])

In [6]:
a[0,...].shape

TensorShape([5, 5, 3])

In [ ]:
a[...,2].shape

TensorShape([1, 5, 5])

In [ ]:
tf.gather_nd(a,[0]).shape

TensorShape([5, 5, 3])

In [ ]:
tf.gather(a,axis=1,indices=[2,3]).shape

TensorShape([1, 2, 5, 3])

**資料重塑**

In [ ]:
a = tf.random.normal([6,32,32,3])

In [ ]:
tf.reshape(a,[6,32*32,3]).shape

TensorShape([6, 1024, 3])

In [ ]:
tf.reshape(a,[6,-1,3]).shape

TensorShape([6, 1024, 3])

In [ ]:
tf.reshape(tf.reshape(a,[6,-1]),[6,16,-1,3]).shape

TensorShape([6, 16, 64, 3])

**資料中的欄位對調**

例如將 [6,32,32,3] 換成 [6,32,3,32]

In [ ]:
tf.transpose(a,perm=[0,1,3,2]).shape


TensorShape([6, 32, 3, 32])

**新增維度**

In [ ]:

a = tf.random.normal([32,32,3])
tf.expand_dims(a,axis=0).shape


TensorShape([1, 32, 32, 3])

**不知道在幹嘛**

In [ ]:
x = tf.random.normal([4,40,12])
(x + tf.random.normal([40,1])).shape

TensorShape([4, 40, 12])

**兩資料合併**

In [ ]:
 #row wise方式合併
a = tf.ones([6,32,3])
b = tf.ones([6,32,3])
tf.concat([a,b],axis=0).shape

TensorShape([12, 32, 3])

In [ ]:
a = tf.ones([6,32,3])
b = tf.ones([6,32,3])
tf.concat([a,b],axis=1).shape

TensorShape([6, 64, 3])

In [ ]:
#column wise方式合併
a = tf.ones([6,32,3])
b = tf.ones([6,32,3])
tf.stack([a,b],axis=0).shape

TensorShape([2, 6, 32, 3])

**分割資料**

In [9]:
#拿掉column 
#unstack
a = tf.ones([2,32,3])
aa,ab= tf.unstack(a,axis=0)
aa.shape

TensorShape([32, 3])

In [10]:
all_data = tf.unstack(a,axis=1)
all_data[0].shape

TensorShape([2, 3])

In [13]:
len(all_data)

32

In [11]:
#針對指定的column然後切分
data_all = tf.split(a,axis=1,num_or_size_splits=2)
data_all[0].shape

TensorShape([2, 16, 3])

In [12]:
len(data_all)

2

**數據運算**

In [15]:
a = tf.fill([2,2],5)
b = tf.fill([2,2],6)
a,b

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[5, 5],
        [5, 5]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[6, 6],
        [6, 6]], dtype=int32)>)

In [ ]:
a+b,a*b

(<tf.Tensor: id=507, shape=(2, 2), dtype=int32, numpy=
 array([[11, 11],
        [11, 11]], dtype=int32)>,
 <tf.Tensor: id=508, shape=(2, 2), dtype=int32, numpy=
 array([[30, 30],
        [30, 30]], dtype=int32)>)

In [16]:
#矩陣相乘
a = tf.fill([2,32,4],5)
b = tf.fill([2,4,6],6)
(a@b).shape

TensorShape([2, 32, 6])

In [18]:
#Dimension wise
#針對特定維度進行運算
#常用情境:用以計算一些loss、計算accuracy

data = [[1,2,3],
      [1,2,3]]
 
tf_data = tf.cast(data,tf.float32)


mean_all = tf.reduce_mean(tf_data, keepdims=False)
mean_0 = tf.reduce_mean(tf_data, axis=0, keepdims=False)
mean_1 = tf.reduce_mean(tf_data, axis=1, keepdims=False)

mean_all,mean_0,mean_1




(<tf.Tensor: shape=(), dtype=float32, numpy=2.0>,
 <tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>,
 <tf.Tensor: shape=(2,), dtype=float32, numpy=array([2., 2.], dtype=float32)>)

**資料排序**


In [ ]:
data = tf.random.normal([10],mean=0,stddev=1)
tf.sort(data,direction='DESCENDING')

<tf.Tensor: id=535, shape=(10,), dtype=float32, numpy=
array([ 1.0939476 ,  0.7920527 ,  0.14045174,  0.09392549,  0.06511419,
       -0.05428518, -0.27255765, -0.33014947, -1.3466002 , -2.3602788 ],
      dtype=float32)>

In [ ]:
tf.gather(data,tf.argsort(data,direction='ASCENDING'))

<tf.Tensor: id=548, shape=(10,), dtype=float32, numpy=
array([-2.3602788 , -1.3466002 , -0.33014947, -0.27255765, -0.05428518,
        0.06511419,  0.09392549,  0.14045174,  0.7920527 ,  1.0939476 ],
      dtype=float32)>

In [ ]:
tf.math.top_k(data,5) #會同時回傳數字以及索引

TopKV2(values=<tf.Tensor: id=550, shape=(5,), dtype=float32, numpy=
array([1.0939476 , 0.7920527 , 0.14045174, 0.09392549, 0.06511419],
      dtype=float32)>, indices=<tf.Tensor: id=551, shape=(5,), dtype=int32, numpy=array([0, 5, 7, 3, 9], dtype=int32)>)

**做padding**

In [ ]:
data = tf.random.normal([3,3],mean=0,stddev=1)

In [ ]:
tf.pad(data,[[1,1],[1,1]])

<tf.Tensor: id=561, shape=(5, 5), dtype=float32, numpy=
array([[ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  1.2887748 , -1.5368944 ,  0.22934034,  0.        ],
       [ 0.        , -0.808462  ,  0.6604852 , -0.728526  ,  0.        ],
       [ 0.        , -0.18216287, -0.7442286 ,  0.4792201 ,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ]],
      dtype=float32)>